import java.util.List;
import org.rannon.core.model.RannonText
import org.rannon.core.model.Tag

rule "add tag rule 0"
    when
        $tags : List()
        $rannonText : RannonText( value.contains("天気")  )
    then
        Tag tag = new Tag("天気予報タグ");
        $tags.add(tag);
end
rule "add tag rule 1"
    when
        $tags : List()
        $rannonText : RannonText( value.contains("お菓子")  )
    then
        Tag tag = new Tag("スイーツタグ");
        $tags.add(tag);
end
