rule "add tag rule 0"
    when
        $annotatedTexts : List()
        $rannonText : RannonText( value.contains("天気")  )
    then
        AnnotatedText at = new AnnotatedText();
        at.setText($rannonText.value());
        at.setTag("天気予報タグ");
        $annotatedTexts.add(at);
end
rule "non add tag rule 0"
    when
        $annotatedTexts : List()
        $rannonText : RannonText( !value.contains("天気")  )
    then
        AnnotatedText at = new AnnotatedText();
        at.setText($rannonText.value());
        at.setTag("");
        $annotatedTexts.add(at);
end