rule "add tag rule TEMPLATE_INDEX"
    when
        $annotatedTexts : List()
        $rannonText : RannonText( value.contains("TEMPLATE_MATCH_TEXT")  )
    then
        AnnotatedText at = new AnnotatedText();
        at.setText($rannonText.value());
        at.setTag("TEMPLATE_TAG");
        $annotatedTexts.add(at);
end
rule "non add tag rule TEMPLATE_INDEX"
    when
        $annotatedTexts : List()
        $rannonText : RannonText( !value.contains("TEMPLATE_MATCH_TEXT")  )
    then
        AnnotatedText at = new AnnotatedText();
        at.setText($rannonText.value());
        at.setTag("");
        $annotatedTexts.add(at);
end