import java.util.List;
import org.rannon.core.model.RannonText
import org.rannon.core.model.AnnotatedText


rule "天気_タグあり"
    when
        $annotatedTexts : List()
        $rannonText : RannonText( value.contains("天気")  )
    then
        AnnotatedText at = new AnnotatedText();
        at.setText($rannonText.value());
        at.setTag("天気予報タグ");
        $annotatedTexts.add(at);
        System.out.println( "ルール発火" );
end

rule "天気_タグなし"
    when
        $annotatedTexts : List()
        $rannonText : RannonText( !value.contains("天気")  )
    then
        AnnotatedText at = new AnnotatedText();
        at.setText($rannonText.value());
        at.setTag("");
        $annotatedTexts.add(at);
        System.out.println( "ルール発火" );
end
